// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiSoftSRB.Database.Audit;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MultiSoftSRB.Database.Audit.Migrations.Main
{
    [DbContext(typeof(MainAuditDbContext))]
    partial class MainAuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("AuditLogSequence");

            modelBuilder.Entity("MultiSoftSRB.Entities.Audit.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"AuditLogSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<long?>("ApiKeyId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChangedProperties")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("MultiSoftSRB.Entities.Audit.AgencyClientAuditLog", b =>
                {
                    b.HasBaseType("MultiSoftSRB.Entities.Audit.AuditLog");

                    b.ToTable("AgencyClients");
                });

            modelBuilder.Entity("MultiSoftSRB.Entities.Audit.ApiKeyAuditLog", b =>
                {
                    b.HasBaseType("MultiSoftSRB.Entities.Audit.AuditLog");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("MultiSoftSRB.Entities.Audit.ApiKeyPermissionAuditLog", b =>
                {
                    b.HasBaseType("MultiSoftSRB.Entities.Audit.AuditLog");

                    b.ToTable("ApiKeyPermissions");
                });

            modelBuilder.Entity("MultiSoftSRB.Entities.Audit.CompanyAuditLog", b =>
                {
                    b.HasBaseType("MultiSoftSRB.Entities.Audit.AuditLog");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("MultiSoftSRB.Entities.Audit.DefaultAuditLog", b =>
                {
                    b.HasBaseType("MultiSoftSRB.Entities.Audit.AuditLog");

                    b.ToTable("DefaultAuditLogs");
                });

            modelBuilder.Entity("MultiSoftSRB.Entities.Audit.RoleAuditLog", b =>
                {
                    b.HasBaseType("MultiSoftSRB.Entities.Audit.AuditLog");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MultiSoftSRB.Entities.Audit.RolePermissionAuditLog", b =>
                {
                    b.HasBaseType("MultiSoftSRB.Entities.Audit.AuditLog");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("MultiSoftSRB.Entities.Audit.UserAuditLog", b =>
                {
                    b.HasBaseType("MultiSoftSRB.Entities.Audit.AuditLog");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MultiSoftSRB.Entities.Audit.UserCompanyAuditLog", b =>
                {
                    b.HasBaseType("MultiSoftSRB.Entities.Audit.AuditLog");

                    b.ToTable("UserCompanies");
                });

            modelBuilder.Entity("MultiSoftSRB.Entities.Audit.UserRoleAuditLog", b =>
                {
                    b.HasBaseType("MultiSoftSRB.Entities.Audit.AuditLog");

                    b.ToTable("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
