// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiSoftSRB.Database.Audit;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MultiSoftSRB.Database.Audit.Migrations.Company
{
    [DbContext(typeof(CompanyAuditDbContext))]
    [Migration("20250328141515_EntityIdIndex")]
    partial class EntityIdIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("AuditLogSequence");

            modelBuilder.Entity("MultiSoftSRB.Entities.Audit.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"AuditLogSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<long?>("ApiKeyId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChangedProperties")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EntityId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("MultiSoftSRB.Entities.Audit.ArticleAuditLog", b =>
                {
                    b.HasBaseType("MultiSoftSRB.Entities.Audit.AuditLog");

                    b.ToTable("ArticleAuditLogs");
                });

            modelBuilder.Entity("MultiSoftSRB.Entities.Audit.DefaultAuditLog", b =>
                {
                    b.HasBaseType("MultiSoftSRB.Entities.Audit.AuditLog");

                    b.ToTable("DefaultAuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
